config/routes.rb
BetterNote::Application.routes.draw do
  root to: "static_pages#root"
  resources :users, only: [:create, :new, :show, :index]# do
  #   resources :friend_requests, only: [:create] do
  #     post "accept", to: "friend_requests#accept"
  #     post "deny", to: "friend_requests#deny"
  #   end
  #   resources :friendships, only: [:destroy]
  # end
  # resources :likes, only: [:destroy]
  # resources :notes, only: [:index, :show, :edit, :update, :destroy] do
  #   resources :comments, only: [:create]
  #   resources :likes, only: [:create]
  # end
  # resources :comments, only: [:destroy]
  # resources :tags
  # resources :notebooks do
  #   resources :notes, only: [:create]
  # end
  resource :session, only: [:create, :new, :destroy]
  namespace :api, defaults: { format: :json } do
    resources :notes, only: [:create, :show, :index, :update, :destroy]
    resources :notebooks, only: [:create, :show, :index, :update, :destroy]
    resources :tags, only: [:index, :create, :update, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :note_tags, only: [:create, :destroy]
    resources :friendships, only: [:destroy]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_signed_in!

  def root
  end
end

app/views/static_pages/_notifications.html.erb
<li>
  <% count = current_user.notifications.count %>
  <span class="notification-count">
    <i class='fa fa-envelope'></i>&nbsp;
    Notifications (<%= count %>)
  </span>
  <ul class="notifications-list">
    <% current_user.notifications.each do |notification| %>
      <li>
        <a href="<%= notification.url %>"><%= notification.text %></a>
      </li>
    <% end %>
  </ul>
</li>

app/views/static_pages/_search_bar.html.erb
<header class="search group">
  <div class="search-left">
    <a href="/#" class="nav-logo">
      <i class='fa fa-file-text'></i>
      BETTERNOTE
    </a>
  </div>
  <div class="search-bar">
    <form action="<%= request.fullpath %>" class="search group" method="GET">
      <input type="text" name="query" value="<%= params[:query] %>">
      <% if params[:note_id] %>
        <input type="hidden" name="note_id" value="<%= params[:note_id] %>">
      <% end %>
      <input type="submit" value="Search">
    </form>
  </div>
  <div class="new-note-button">
  </div>
</header>

app/views/static_pages/_sidebar.html.erb
<section class="sidebar">
  <article class="sidebar-item">
    <div class="sidebar-header group">
      <div class="sidebar-header-left">
        <i class="fa fa-caret-down"></i>&nbsp;
        Notebooks
      </div>
      <div class="sidebar-header-right">
        <i class="fa fa-toggle-down"></i>
        <ul class="options-dropdown">
          <li>
            <a href="<%= new_notebook_url %>" class="group">
              New Notebook...
            </a>
          </li>
        </ul>
      </div>
    </div>
    <%= render partial: "notebooks/index" %>
  </article>

  <article class="sidebar-item">
    <div class="sidebar-header group">
      <div class="sidebar-header-left">
        <i class="fa fa-caret-down"></i>&nbsp;
        Tags
      </div>
      <div class="sidebar-header-right">
        <i class="fa fa-toggle-down"></i>
        <ul class="options-dropdown">
          <li>
            <a href="<%= new_tag_url %>" class="group">
              New Tag...
            </a>
          </li>
        </ul>
      </div>
    </div>
    <%= render partial: "tags/index" %>
  </article>

  <article class="sidebar-item">
    <div class="sidebar-header group">
      <div class="sidebar-header-left">
        <i class="fa fa-caret-down"></i>&nbsp;
        Friends
      </div>
      <div class="sidebar-header-right">
        <i class="fa fa-toggle-down"></i>
        <ul class="options-dropdown">
          <li>
            <a href="<%= users_url %>" class="group">
              View All Users
            </a>
          </li>
        </ul>
      </div>
    </div>
    <%= render partial: "users/friends" %>
  </article>
</section>

app/views/static_pages/root.html.erb
<section class="notes-list">
</section>

<section class="note-show">
</section>