config/routes.rb
BetterNote::Application.routes.draw do
  root to: "static_pages#root"
  resources :users, only: [:create, :new, :show, :index]# do
  #   resources :friend_requests, only: [:create] do
  #     post "accept", to: "friend_requests#accept"
  #     post "deny", to: "friend_requests#deny"
  #   end
  #   resources :friendships, only: [:destroy]
  # end
  # resources :likes, only: [:destroy]
  # resources :notes, only: [:index, :show, :edit, :update, :destroy] do
  #   resources :comments, only: [:create]
  #   resources :likes, only: [:create]
  # end
  # resources :comments, only: [:destroy]
  # resources :tags
  # resources :notebooks do
  #   resources :notes, only: [:create]
  # end
  resource :session, only: [:create, :new, :destroy]
  namespace :api, defaults: { format: :json } do
    resources :notes, only: [:create, :show, :index, :update, :destroy]
    resources :notebooks, only: [:create, :show, :index, :update, :destroy]
    resources :tags, only: [:index, :create, :update, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :note_tags, only: [:create, :destroy]
    resources :friendships, only: [:destroy]
  end
end

app/models/notebook.rb
class Notebook < ActiveRecord::Base
  validates :name, :owner, presence: true

  has_many :notes, inverse_of: :notebook, dependent: :destroy
  belongs_to :owner, class_name: "User"
end

app/controllers/api/notebooks_controller.rb
class Api::NotebooksController < ApplicationController
  before_action :require_signed_in!
  before_action :user_owns_notebook?, only: [:edit, :update, :destroy, :show]

  def create
    @notebook = current_user.notebooks.new(notebook_params)
    if @notebook.save
      render json: @notebook
    else
      render json: @notebook.errors.full_messages, status: :unprocessable_entity
    end
  end

  def index
    @notebooks = current_user.notebooks
    render "notebooks/index"
  end

  def show
    @notebook = Notebook.includes(:notes).find(params[:id])
    render "notebooks/show"
  end

  def update
    @notebook = Notebook.includes(:notes).find(params[:id])
    if @notebook.update_attributes(notebook_params)
      render json: @notebook.to_json(include: :notes)
    else
      render json: @notebook.errors.full_messages, status: :unprocessable_entity
    end
  end

  def destroy
    @notebook = Notebook.find(params[:id])
    @notebook.destroy
    render json: {}
  end

  private
  def notebook_params
    params.require(:notebook).permit(:name)
  end

  def user_owns_notebook?
    @notebook = Notebook.find(params[:id])
    redirect_to root_url unless @notebook.owner == current_user
  end
end

app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController
  before_action :require_signed_in!
  before_action :user_owns_notebook?, only: [:edit, :update, :destroy, :show]

  def new
    @notebook = current_user.notebooks.new
    render :new
  end

  def create
    @notebook = current_user.notebooks.new(notebook_params)
    if @notebook.save
      redirect_to root_url
    else
      flash.now[:errors] = @notebook.errors.full_messages
      render :new
    end
  end

  def index
    @notebooks = current_user.notebooks
    render :index
  end

  def show
    @notebooks = Notebook.all
    @notebook = Notebook.includes(:notes).find(params[:id])

    if params[:note_id] && @note = Note.find_by(id: params[:note_id])
    else
      redirect_to notebook_url(@notebook, note_id:
        @notebook.notes.sort_by { |n| n.created_at }.last.id)
      return
    end

    if params[:query] && params[:query] != ""
      @notes = @notebook.notes.search_by_title_and_body(params[:query])
      render :show
      return
    else
      @notes = @notebook.notes
      render :show
    end
  end

  def edit
    @notebook = Notebook.find(params[:id])
    render :edit
  end

  def update
    @notebook = Notebook.find(params[:id])
    if @notebook.update_attributes(notebook_params)
      redirect_to
    else
      flash.now[:errors] = @notebook.errors.full_messages
      render :edit
    end
  end

  def destroy
    @notebook = Notebook.find(params[:id])
    @notebook.destroy
    redirect_to root_url
  end

  private
  def notebook_params
    params.require(:notebook).permit(:name)
  end

  def user_owns_notebook?
    @notebook = Notebook.find(params[:id])
    redirect_to root_url unless @notebook.owner == current_user
  end
end

app/views/notebooks/_form.html.erb
<% action = (@notebook.new_record?) ?
      notebooks_url :
      notebook_url(@notebook) %>
<% button_value = (@notebook.new_record?) ?
      "Create New Notebook" : "Save" %>

<form action="<%= action %>" method="post" class="notebook group">
  <%= auth_token %>

  <% unless @notebook.new_record? %>
    <input type="hidden" name="_method" value="put">
  <% end %>

  <div class="input">
    <label for="notebook-name">Notebook Name</label>
    <input type="text" name="notebook[name]"
        id="notebook-name" value="<%= @notebook.name %>">
  </div>

  <div class="submit">
    <input type="submit" value="<%= button_value %>">
  </div>
</form>

app/views/notebooks/_index.html.erb
<ul class="sidebar-list">
  <li class="group">
    <div class="sidebar-entry-left">
      <a href="<%= notes_url %>" class="group">
          <i class='fa fa-book fa-lg'></i>&nbsp;
          All Notes (<%= current_user.notes.count %>)
      </a>
    </div>
  </li>
  <% current_user.notebooks.each do |notebook| %>
    <% next unless notebook.persisted? %>
    <li class="group">
      <div class="sidebar-entry-left">
        <a href="<%= notebook_url(notebook) %>">
            <i class='fa fa-book fa-lg'></i>&nbsp;
            <%= notebook.name %> (<%= notebook.notes.count %>)
        </a>
      </div>
      <div class="sidebar-entry-right">
        <i class='fa fa-toggle-down'></i>
        <ul class="options-dropdown">
          <li>
            <a href="<%= edit_notebook_url(notebook) %>">
              Rename...
            </a>
          </li>
          <li>
            <%= button_to "Delete Notebook",
              notebook_url(notebook), method: :delete %>
          </li>
        </ul>
      </div>
    </li>
  <% end %>
</ul>

app/views/notebooks/edit.html.erb
<section class="left-margin-no-list popup">
  <h3>Rename Notebook</h3>
  <%= render partial: "form" %>
</section>

app/views/notebooks/new.html.erb
<section class="left-margin-no-list popup">
  <h3>New Notebook</h3>
  <%= render partial: "form" %>
</section>

app/views/notebooks/show.html.erb
<section class="notes-list">
  <div class="notes-list-header">
    <i class="fa fa-book"></i>
    <%= @notebook.name %>
  </div>
  <ul class="notes">
    <% notes = @notes.sort_by! { |note| note.created_at }.reverse! %>
    <% notes.each do |note| %>
      <li>
        <a href="<%= update_url_with_note(request.fullpath.dup, note) %>">
          <%= render partial: "notes/preview", locals: { note: note } %>
        </a>
      </li>
    <% end %>
  </ul>
  <%= render partial: "notes/list_footer" %>
</section>

</div> <%# closes "left-absolute div" %>

<% if @note || notes.first %>
  <%= render partial: "notes/show",
    locals: { note: @note || notes.first } %>
<% end %>