config/routes.rb
BetterNote::Application.routes.draw do
  root to: "static_pages#root"
  resources :users, only: [:create, :new, :show, :index]# do
  #   resources :friend_requests, only: [:create] do
  #     post "accept", to: "friend_requests#accept"
  #     post "deny", to: "friend_requests#deny"
  #   end
  #   resources :friendships, only: [:destroy]
  # end
  # resources :likes, only: [:destroy]
  # resources :notes, only: [:index, :show, :edit, :update, :destroy] do
  #   resources :comments, only: [:create]
  #   resources :likes, only: [:create]
  # end
  # resources :comments, only: [:destroy]
  # resources :tags
  # resources :notebooks do
  #   resources :notes, only: [:create]
  # end
  resource :session, only: [:create, :new, :destroy]
  namespace :api, defaults: { format: :json } do
    resources :notes, only: [:create, :show, :index, :update, :destroy]
    resources :notebooks, only: [:create, :show, :index, :update, :destroy]
    resources :tags, only: [:index, :create, :update, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :note_tags, only: [:create, :destroy]
    resources :friendships, only: [:destroy]
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  validates :author, :notebook, presence: true

  include PgSearch

  pg_search_scope :search_by_title_and_body, against: [:title, :body]

  belongs_to(
    :author,
    class_name: User,
    foreign_key: :author_id,
    primary_key: :id
  )

  belongs_to :notebook
  has_many :comments, inverse_of: :note, dependent: :destroy
  has_many :note_tags, inverse_of: :note, dependent: :destroy
  has_many :tags, through: :note_tags, source: :tag
  has_many :likes, inverse_of: :note, dependent: :destroy
  has_many :likers, through: :likes, source: :owner
end

app/controllers/api/notes_controller.rb
class Api::NotesController < ApplicationController
  before_action :require_signed_in!
  before_action :user_owns_note?, only: [:edit, :update, :destroy]
  before_action :authorized?, only: [:show]

  def index
    @notes = current_user.notes.includes(:comments, :notebook, :tags)
    render partial: "notes/index", locals: { notes: @notes }
  end

  def create
    @note = current_user.notes.new(note_params)
    if @note.save
      render json: @note
    else
      render json: @note.errors.full_messages, status: :unprocessable_entity
    end
  end

  def edit
    @note = Note.find(params[:id])
    render json: @note
  end

  def update
    @note = Note.find(params[:id])
    @note.assign_attributes(note_params)

    if @note.save
      render partial: "notes/show", locals: { note: @note }
    else
      render json: @note.errors.full_messages, status: :unprocessable_entity
    end
  end

  def show
    @note = Note.includes(:comments, :notebook, :tags).find(params[:id])
    render partial: "notes/show", locals: { note: @note }
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    render json: {}
  end

  private
  def user_owns_note?
    @note = Note.find(params[:id])
    redirect_to root_url unless @note.author == current_user
  end

  def authorized?
    author = Note.find(params[:id]).author
    unless (current_user == author || user.find_friendship(current_user))
      redirect_to root_url
    end
  end

  def note_params
    params.require(:note).permit(:title, :body, :notebook_id)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :require_signed_in!
  before_action :user_owns_note?, only: [:edit, :update, :destroy]
  before_action :authorized?, only: [:show]

  def create
    @note = current_user.notes.new(note_params)
    if @note.save
      redirect_to notebook_url(@note.notebook, note_id: @note.id)
    else
      flash.now[:errors] = @note.errors.full_messages
      render :new
    end
  end

  def index
    @notebooks = Notebook.all

    if params[:note_id] && @note = Note.where(id: params[:note_id]).first
      @note = Note.find(params[:note_id])
    else
      redirect_to notes_url(note_id:
        Note.all.sort_by { |n| n.created_at }.last.id)
      return
    end

    if params[:query] && params[:query] != ""
      @notes = current_user.notes.search_by_title_and_body(params[:query])
      render :index
      return
    else
      @notes = current_user.notes
      render :index
    end
  end

  def update
    @note = Note.find(params[:id])

    @note.assign_attributes(note_params)
    @note.tag_ids = note_tag_params[:tag_ids]

    if @note.save
      redirect_to request.env["HTTP_REFERER"].gsub("&edit=true", "")
    else
      flash[:errors] = @note.errors.full_messages
      redirect_to :back
    end
  end

  def show
    @note = Note.find(params[:id])
    render :show
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    redirect_to :back
  end

  private
  def user_owns_note?
    @note = Note.find(params[:id])
    redirect_to root_url unless @note.author == current_user
  end

  def authorized?
    author = Note.find(params[:id]).author
    unless (current_user == author || user.find_friendship(current_user))
      redirect_to root_url
    end
  end

  def note_params
    params.require(:note).permit(:title, :body, :notebook_id)
  end

  def note_tag_params
    params.require(:note_tags).permit(tag_ids: [])
  end
end

app/views/notes/_comments.html.erb
<section class="comments">
  <header class="comments-header group">
    <div class="note-show-header-left">
      <i class="fa fa-comments"></i>&nbsp;
      Comments
    </div>
  </header>
    <% if comments.count == 0 && !params[:new_comment] %>
      <div class="comment-list-text">
        No comments
      </div>
    <% end %>
  <ul class="comments-list">
    <% comments.each do |comment| %>
      <li>
        <div class="comment-body">
          <%= comment.body %>
        </div>
        <div class="comment-info group">
          <div class="comment-info-left">
            Posted by <%= comment.author.username %>
            <%= time_ago_in_words(comment.created_at) %> ago
          </div>
          <div class="comment-info-right">
            <% if comment.author == current_user %>
              <form action="<%= comment_url(comment) %>" method="post">
                <%= auth_token %>
                <input type="hidden" name="_method" value="delete">
                <button class="note-show-button comment">
                  DELETE&nbsp;
                  <i class="fa fa-trash-o"></i>
                </button>
              </form>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>

  <% if params[:new_comment] %>
    <%= render partial: "comments/form", locals: { note: note } %>
  <% else %>
    <div class="new-comment">
      <a href="<%= request.fullpath + "&new_comment=true" %>">
        <i class="fa fa-plus"></i>&nbsp;
        New Comment
      </a>
    </div>
  <% end %>
</section>

app/views/notes/_edit.html.erb
<form action="<%= note_url(note) %>" method="post" class="note-form">
  <%= auth_token %>

  <input type="hidden" name="_method" value="put">

  <div class="input note-title">
    <input type="text" name="note[title]"
      id="note-title" value="<%= note.title %>">
  </div>

  <div class="input note-body">
    <textarea name="note[body]" id="note-body"><%= note.body %></textarea>
  </div>

  <div class="input">
    <label for="note-notebook">Notebook</label>
    <select name="note[notebook_id]" id="note-notebook">
      <% current_user.notebooks.each do |notebook| %>
        <option value="<%= notebook.id %>"
          <%= "selected" if (notebook.id == note.notebook.id) %>>
          <%= notebook.name %>
        </option>
      <% end %>
    </select>
  </div>

  <div class="input">
    <label="note-tags">Tags</label>
    <input type="hidden" name="note_tags[tag_ids][]" value="">
    <% current_user.tags.each_with_index do |tag, i| %>
      <input type="checkbox"
              name="note_tags[tag_ids][]"
              value="<%= tag.id %>"
              <%= "checked" if note.tags.include?(tag) %>>
        <%= tag.name %>
      </input>
      <br>
    <% end %>
  </div>

  <div class="submit button">
    <input type="submit" value="Submit">
  </div>
</form>

app/views/notes/_index.html.erb
<section class="notes-list">
  <div class="notes-list-header">
    <i class="fa fa-book"></i>&nbsp;
    All Notes
  </div>
  <ul class="notes">
    <% notes = @notes.sort_by! { |note| note.created_at }.reverse! %>
    <% notes.each do |note| %>
      <li>
        <a href="<%= update_url_with_note(request.fullpath.dup, note) %>">
          <%= render partial: "notes/preview", locals: { note: note } %>
        </a>
      </li>
    <% end %>
  </ul>
  <%= render partial: "notes/list_footer" %>
</section>

</div> <%# closes "left-absolute div" %>

<% if @note || notes.first %>
  <%= render partial: "notes/show",
    locals: { note: @note || notes.first } %>
<% end %>

app/views/notes/_info.html.erb
<table class="note-info">
  <tr>
    <td class="note-info-field">Title:</td>
    <td class="note-info-data"><%= note.title %></td>
  </tr>
  <tr>
    <td class="note-info-field">Author:</td>
    <td class="note-info-data"><%= note.author.username %></td>
  </tr>
  <tr>
    <td class="note-info-field">Created At:</td>
    <td class="note-info-data"><%= note.created_at.strftime("%b %d, %Y") %></td>
  </tr>
  <tr>
    <td class="note-info-field">Updated At:</td>
    <td class="note-info-data"><%= note.updated_at.strftime("%b %d, %Y") %></td>
  </tr>
  <tr>
    <td class="note-info-field">Notebook:</td>
    <td class="note-info-data"><%= note.notebook.name %></td>
  </tr>
  <tr>
    <td class="note-info-field">Tags:</td>
    <td class="note-info-data">
      <% if note.tags.length > 0 %>
        <ul class="tags">
          <% note.tags.each do |tag| %>
            <li>
              <%= tag.name %>
            </li>
          <% end %>
        </ul>
      <% else %>
        No tags
      <% end %>
    </td>
  </tr>
  <tr>
    <td class="note-info-field">Likes:</td>
    <td class="note-info-data">
      <%= note.likes.count.to_s + " " + "like".pluralize(note.likes.count) %>
    </td>
  </tr>
</table>

app/views/notes/_list_footer.html.erb
<div class="notes-list-footer group">
  <div class="notes-list-footer-left">
      View Options
      <i class="fa fa-caret-up"></i>
    <ul class="options-dropdown">
      <li class="options-dropdown-header">
        Sort By
      </li>
      <li>
        <a href="#">
          Date Created (newest first)
        </a>
      </li>
      <li>
        <a href="#">
          Date Created (oldest first)
        </a>
      </li>
      <li>
        <a href="#">
          Date Updated (newest first)
        </a>
      </li>
      <li>
        <a href="#">
          Date Updated (oldest first)
        </a>
      </li>
      <li>
        <a href="#">
          Title (ascending)
        </a>
      </li>
      <li>
        <a href="#">
          Title (descending)
        </a>
      </li>
    </ul>
  </div>
  <div class="notes-list-footer-right">
    Notes counter TK
  </div>
</div>

app/views/notes/_new.html.erb
<form action="<%= notebook_notes_url(notebook) %>" method="post">
  <%= auth_token %>

  <input type="hidden" name="note[notebook_id]" value="<%= notebook.id %>">

  <button type="submit">
    <i class="fa fa-plus"></i>&nbsp;
    New Note
  </button>
</form>

app/views/notes/_preview.html.erb
<article class="note-preview">
  <div class="note-preview-title">
    <%= note.title %>
  </div>
  <div class="note-preview-body">
    <span class="note-preview-time">
      <%= time_ago_in_words(note.created_at) %> ago
    </span>
    <%= note.body %>
  </div>
</article>

app/views/notes/_show.html.erb
<section class="note-show">
  <%= render partial: "notes/show_header", locals: { note: note } %>
  <% if params[:edit] %>
    <div class="note-content">
      <%= render partial: "notes/edit", locals: { note: note } %>
    </div>
  <% else %>
    <div class="note-content">
      <div class="note-title">
          <%= note.title %>
      </div>
      <div class="note-body">
        <%= note.body %>
      </div>
    </div>
  <% end %>
  <%= render partial: "notes/comments",
    locals: { comments: note.comments, note: note } %>
</section>

app/views/notes/_show_header.html.erb
<header class="note-show-top group">
  <div class="note-show-header-left">
    <div class="notebook-name group">
      <div class="notebook-name-text">
        <%= note.notebook.name %>
        &nbsp;<i class="fa fa-angle-down"></i>
      </div>
      <ul class="options-dropdown">
        <% current_user.notebooks.each do |notebook| %>
        <li>
          <a href="#"><%= notebook.name %></a>
        </li>
        <% end %>
      </ul>
    </div>
    <ul class="tags">
      <% note.tags.each do |tag| %>
        <li>
          <%= tag.name %>
        </li>
      <% end %>
      <li>
        <%= note.tags.length > 0 ? "+  " : "+ Tag  " %>
      </li>
    </ul>
  </div>
  <div class="note-show-header-right">
    <div class="info-text">
      INFO&nbsp;
      <i class="fa fa-info-circle"></i>
    </div>
    <%= render partial: "notes/info", locals: { note: note }%>
  </div>
</header>
<header class="note-show-bottom group">
  <div class="note-show-header-left">
    <ul class="dates">
      <li>
        Created: <%= note.created_at.strftime("%b %d, %Y")  %>
      </li>
      <li>
        Modified: <%= note.updated_at.strftime("%b %d, %Y")  %>
      </li>
    </ul>
  </div>
  <div class="note-show-header-right">
    <% if note.likers.include?(current_user) %>
      <form action="<%= like_url(note.likes.find_by(
          {owner_id: current_user.id})) %>" method="post">
        <%= auth_token %>
        <input type="hidden" name="_method" value="delete">
        <button class="note-show-button">
          REMOVE LIKE
          <i class="fa fa-thumbs-o-down"></i>
        </button>
      </form>
    <% else %>
    <form action="<%= note_likes_url(note) %>" method="post">
      <%= auth_token %>
      <button class="note-show-button">
        LIKE
        <i class="fa fa-thumbs-o-up"></i>
      </button>
    </form>
    <% end %>
    <% if current_user == note.author %>
      <a href="<%= request.url + "&edit=true" %>" class="note-show-button">
        EDIT
        <i class="fa fa-file-text-o"></i>
      </a>
      <form action="<%= note_url(note) %>" method="post">
        <%= auth_token %>
        <input type="hidden" name="_method" value="delete">
        <button class="note-show-button">
          DELETE
          <i class="fa fa-trash-o"></i>
        </button>
      </form>
    <% end %>
  </div>
</header>

app/views/notes/edit.html.erb
<h1>Edit Note</h1>
<form action="<%= user_note_url(current_user, @note) %>" method="post" class="note">
  <%= auth_token %>

  <input type="hidden" name="_method" value="put">

  <div class="input">
    <label for="note-title">Title</label>
    <input type="text" name="note[title]"
      id="note-title" value="<%= @note.title %>">
  </div>

  <div class="input">
    <label for="note-body"> Body</label>
    <textarea name="note[body]" id="note-body"><%= @note.body %></textarea>
  </div>

  <div class="input">
    <label for="note-notebook">Notebook</label>
    <select name="note[notebook_id]" id="note-notebook">
      <% current_user.notebooks.each do |notebook| %>
        <option value="<%= notebook.id %>"
          <%= "selected" if (notebook.id == @note.notebook.id) %>>
          <%= notebook.name %>
        </option>
      <% end %>
    </select>
  </div>

  <div class="input">
    <label="note-tags">Tags</label>
    <input type="hidden" name="note_tags[tag_ids][]" value="">
    <% current_user.tags.each_with_index do |tag, i| %>
      <input type="checkbox"
              name="note_tags[tag_ids][]"
              value="<%= tag.id %>"
              <%= "checked" if @note.tags.include?(tag) %>>
        <%= tag.name %>
      </input>
      <br>
    <% end %>
  </div>

  <div class="submit">
    <input type="submit" value="Submit">
  </div>
</form>

app/views/notes/index.html.erb
<% if params[:list_view] == "notebook" %>
  <%= render "notebooks/show" %>
<% elsif params[:list_view] == "tag" %>
  <%= render "tags/show" %>
<% elsif params[:list_view] == "friend" %>
  <%= render "users/show" %>
<% else %>
  <%= render "notes/index" %>
<% end %>

app/views/notes/show.html.erb
<h1>Note Show Page</h1>

<section class="note-show">
  <div class="note-title">
    Title: <%= @note.title %>
  </div>
  <div class="note-body">
    Body: <%= @note.body %>
  </p>

  <div class="note-info">
    <h2>Note Information:</h2>
    <%= render partial: "info_old" %>
  </div>

  <div class="note-options">
    <% if @note.likers.include?(current_user) %>
      <%= button_to "Remove Like",
        user_note_like_url(@note.author, @note, @note.likes.find_by(
          {owner_id: current_user.id})), method: :delete %>
    <% else %>
      <%= button_to "Like Note",
        user_note_likes_url(@note.author, @note), method: :post %>
    <% end %>
    <% if current_user == @note.author %>
      <%= button_to "Edit Note", edit_user_note_url(current_user, @note), method: :get %>
      <%= button_to "Delete Note", user_note_url(current_user, @note), method: :delete %>
    <% end %>
  </div>

  <div class="note-comments">
  <h2>Comments:</h2>
    <%= render partial: "comments", locals: { comments: @note.comments, note: @note } %>
  </div>
</section>