config/routes.rb
BetterNote::Application.routes.draw do
  root to: "static_pages#root"
  resources :users, only: [:create, :new, :show, :index]# do
  #   resources :friend_requests, only: [:create] do
  #     post "accept", to: "friend_requests#accept"
  #     post "deny", to: "friend_requests#deny"
  #   end
  #   resources :friendships, only: [:destroy]
  # end
  # resources :likes, only: [:destroy]
  # resources :notes, only: [:index, :show, :edit, :update, :destroy] do
  #   resources :comments, only: [:create]
  #   resources :likes, only: [:create]
  # end
  # resources :comments, only: [:destroy]
  # resources :tags
  # resources :notebooks do
  #   resources :notes, only: [:create]
  # end
  resource :session, only: [:create, :new, :destroy]
  namespace :api, defaults: { format: :json } do
    resources :notes, only: [:create, :show, :index, :update, :destroy]
    resources :notebooks, only: [:create, :show, :index, :update, :destroy]
    resources :tags, only: [:index, :create, :update, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :note_tags, only: [:create, :destroy]
    resources :friendships, only: [:destroy]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  validates :username, :email, :password_digest, presence: true
  validates :username, :email, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :session_token, presence: true
  before_validation :ensure_session_token

  has_many(
    :notes,
    foreign_key: :author_id,
    inverse_of: :author,
    dependent: :destroy
  )

  has_many(
    :notebooks,
    foreign_key: :owner_id,
    inverse_of: :owner,
    dependent: :destroy
  )

  has_many(
    :tags,
    foreign_key: :owner_id,
    inverse_of: :owner,
    dependent: :destroy
  )

  has_many(
    :comments,
    foreign_key: :author_id,
    inverse_of: :author,
    dependent: :destroy
  )

  has_many(
    :likes,
    foreign_key: :owner_id,
    inverse_of: :owner,
    dependent: :destroy
  )

  has_many(
    :friendships,
    foreign_key: :out_friend_id,
    inverse_of: :out_friend,
    dependent: :destroy
  )

  has_many :friends, through: :friendships, source: :in_friend

  has_many(
    :friend_requests,
    foreign_key: :out_friend_id,
    inverse_of: :out_friend,
    dependent: :destroy
  )

  has_many :notifications, inverse_of: :user, dependent: :destroy

  has_many :pending_friends, through: :friend_requests, source: :in_friend

  def self.generate_random_token
    SecureRandom.urlsafe_base64
  end

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password) if password
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_random_token
    self.save!
    self.session_token
  end

  def friend?(other_user)
    self.friends.include?(other_user)
  end

  def pending_friend?(other_user)
    self.pending_friends.include?(other_user)
  end

  def find_friend_request(other_user)
    self.friend_requests.where({in_friend: other_user}).first
  end

  def find_friendship(other_user)
    self.friendships.where({in_friend: other_user}).first
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_random_token
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signed_out!, only: [:new, :create]
  before_action :authorized?, only: [:show]

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      @user.notebooks.create({
        name: "First notebook!"
      })
      @user.notes.create({
        title: "Welcome to BetterNote!",
        body: "",
        notebook_id: @user.notebooks.first.id
      })
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new, layout: "public"
    end
  end

  def new
    @user = User.new
    render :new, layout: "public"
  end

  def index
    @users = User.all
    @users.delete_at(@users.find_index(current_user))
    render :index
  end

  def show
    @user = User.includes(:notes).find(params[:id])
    @notebooks = Notebook.all

    if params[:note_id] && @note = Note.where(id: params[:note_id]).first
      @note = Note.find(params[:note_id])
    else
      redirect_to user_url(@user, note_id:
        @user.notes.sort_by { |n| n.created_at }.last.id)
      return
    end

    if params[:query] && params[:query] != ""
      @notes = @user.notes.search_by_title_and_body(params[:query])
      render :show
      return
    else
      @notes = @user.notes
      render :show
    end
  end

  private
  def authorized?
    user = User.find(params[:id])
    unless (current_user == user || user.find_friendship(current_user))
      redirect_to root_url
    end
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/views/users/_friends.html.erb
<ul class="sidebar-list">
  <% current_user.friends.each do |friend| %>
    <li class="group">
      <div class="sidebar-entry-left">
        <a href="<%= user_url(friend) %>">
            <i class='fa fa-user fa-lg'></i>&nbsp;
            <%= friend.username %>
        </a>
      </div>
      <div class="sidebar-entry-right">
        <i class='fa fa-toggle-down'></i>
        <ul class="options-dropdown">
          <li>
            <%= button_to "Remove Friend",
              user_friendship_url(current_user, current_user.find_friendship(friend)),
              method: :delete %>
          </li>
        </ul>
      </div>
    </li>
  <% end %>
</ul>

app/views/users/index.html.erb
<section class="left-margin-no-list">
  <h1>All Users</h1>

  <ul class="users">
    <% @users.each do |user| %>
      <li>
        <%= user.username %>
        <% if current_user.friend?(user) %>
          <%= button_to "Remove Friend",
            user_friendship_url(current_user, current_user.find_friendship(user)),
            method: :delete %>
        <% elsif current_user.pending_friend?(user) %>
          <div class="friend-pending">Friend Request Pending...</div>
        <% elsif user.pending_friend?(current_user) %>
          <% friend_request = user.find_friend_request(current_user) %>
          <%= button_to "Accept Friend Request",
                user_friend_request_accept_url(current_user, friend_request) %>
          <%= button_to "Deny Friend Request",
                user_friend_request_deny_url(current_user, friend_request) %>
        <% else %>
          <%= button_to "Add Friend",
            user_friend_requests_url(user) %>
        <% end %>
      </li>
    <% end %>
  </ul>
</section>

  <li>
    <a href="<%= new_notebook_url %>" class="group">
      <div class="sidebar-entry-left">
        <i class="fa fa-plus"></i>&nbsp;
        Add New Notebook
      </div>
    </a>
  </li>

app/views/users/new.html.erb
<form action="<%= users_url %>" method="post">
  <%= auth_token %>

  <div class="heading group">
    <h2>Sign Up</h2>
    <div class="new-account">
      or <a href="<%= new_session_url %>">Sign In</a>
    </div>
  </div>

  <div class="input">
    <label class="user-username">Username</label>
    <input type="text" name="user[username]" id="user-username">
  </div>

  <div class="input">
    <label class="user-email">Email</label>
    <input type="email" name="user[email]" id="user-email">
  </div>

  <div class="input">
    <label class="user-password">Password</label>
    <input type="password" name="user[password]" id="user-password">
  </div>

  <div class="submit">
    <input type="submit" value="Submit">
  </div>
</form>

app/views/users/show.html.erb
<section class="notes-list">
  <div class="notes-list-header">
    <i class='fa fa-user fa-lg'></i>&nbsp;
    <%= @user.username %>
  </div>
  <ul class="notes">
    <% notes = @notes.sort_by! { |note| note.created_at }.reverse! %>
    <% notes.each do |note| %>
      <li>
        <a href="<%= update_url_with_note(request.fullpath.dup, note) %>">
          <%= render partial: "notes/preview", locals: { note: note } %>
        </a>
      </li>
    <% end %>
  </ul>
  <%= render partial: "notes/list_footer" %>
</section>

</div> <!-- closes "left-absolute div" -->

<% if @note || notes.first %>
  <%= render partial: "notes/show",
    locals: { note: @note || notes.first } %>
<% end %>